# permissions for end users to edit productchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eolctl-operator
    app.kubernetes.io/managed-by: kustomize
  name: productcheck-editor-role
rules:
- apiGroups:
  - eol.endoflife.io
  resources:
  - productchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eol.endoflife.io
  resources:
  - productchecks/status
  verbs:
  - get
